import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa6";
import {
  LuBinary,
  LuDatabase,
  LuDatabaseZap,
  LuDrama,
  LuGlobe,
  LuNetwork,
  LuPackage,
  LuPaintbrush,
  LuPlug,
} from "react-icons/lu";
import {
  SiDocker,
  SiExpress,
  SiFigma,
  SiFlask,
  SiGit,
  SiGithubactions,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiTypst,
  SiVuedotjs,
} from "react-icons/si";

// Simple Icons has no gRPC/StyleX/Playwright/etc., so those use generic Lucide glyphs.
export const skillIcons: Record<string, IconType> = {
  Golang: SiGo,
  Python: SiPython,
  gRPC: LuNetwork,
  ConnectRPC: LuPlug,
  "Protocol Buffers": LuBinary,
  "REST APIs": LuGlobe,
  GraphQL: SiGraphql,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  Flask: SiFlask,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Svelte: SiSvelte,
  SvelteKit: SiSvelte,
  Vue: SiVuedotjs,
  React: SiReact,
  "Tailwind CSS": SiTailwindcss,
  StyleX: LuPaintbrush,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  "Ent ORM": LuDatabase,
  SQLC: LuDatabaseZap,
  AWS: FaAws,
  GCP: SiGooglecloud,
  Docker: SiDocker,
  Git: SiGit,
  Buf: LuPackage,
  Typst: SiTypst,
  "GitHub Actions": SiGithubactions,
  Figma: SiFigma,
  Playwright: LuDrama,
};
